l_english:
 anb_settings.1.t:0 "Welcome to:\n£settings_main_bg£"
 anb_settings.1.d:2 "§L                                            The Inheritors of Insyaa Update           EU4 version 1.37.5"
 anb_settings.1.a:0 "£settings_button_regions_menu£"
 anb_settings.1.b:0 "£settings_button_conquerors_menu£"
 anb_settings.1.bx:0 "£settings_button_conquerors_menu_g£"
 anb_settings.1.c:0 "£settings_button_achievements_off£"
 anb_settings.1.cx:0 "£settings_button_achievements_on£"
 anb_settings.1.s:0 "£settings_button_start_game£"
 anb_settings.1.empty:0 "£event_button_settings_empty£"

 anb_settings.2.t:0 "Great Conquerors\n£settings_conqueror_bg£"
 anb_settings.2.d:0 ""
 anb_settings.2.a:0 "£settings_button_no_conqueror_g£"
 anb_settings.2.ax:0 "£settings_button_no_conqueror£"
 anb_settings.2.b:0 "£settings_button_conqueror_g£"
 anb_settings.2.bx:0 "£settings_button_conqueror£"
 anb_settings.2.c:0 "£settings_button_mythical_g£"
 anb_settings.2.cx:0 "£settings_button_mythical£"
 anb_settings.2.dd:0 "£settings_button_conqueror_variance_off£"
 anb_settings.2.ddx:0 "£settings_button_conqueror_variance_on£"
 anb_settings.2.e:0 "£settings_button_conqueror_delay_off£"
 anb_settings.2.ex:0 "£settings_button_conqueror_delay_on£"
 anb_settings.2.x:0 "£settings_button_back_to_menu_2£"
 
 anb_settings.3.t:0 "£settings_regions_bg£\n    [Root.GetSettingsNorthAelantir]\n    [Root.GetSettingsCannor]\n    [Root.GetSettingsForbiddenPlains]\n    [Root.GetSettingsWestSerpentspine]\n    [Root.GetSettingsHaless]\n    [Root.GetSettingsDeepwoods]\n    [Root.GetSettingsBulwar]\n    [Root.GetSettingsEastSerpentspine]\n    [Root.GetSettingsRahen]\n    [Root.GetSettingsNorthSarhal]\n    [Root.GetSettingsInsyaa]\n    [Root.GetSettingsSouthAelantir]\n    [Root.GetSettingsSouthSarhal]\n    [Root.GetSettingsEastSarhal]\n    [Root.GetSettingsGozenguun]"
 anb_settings.3.d:0 "\n\n\n\n[Root.GetSettingsAlertRed][Root.GetSettingsAlertOrange]"
 anb_settings.3.a:0 "£settings_button_all££settings_alert_none£"
 anb_settings.3.ax:0 "£settings_button_all_x££settings_alert_none£"
 anb_settings.3.b:0 "£settings_button_north_aelantir££settings_alert_none£"
 anb_settings.3.bx:0 "£settings_button_north_aelantir_x£[Root.GetSettingsAlertNorthAelantir]"
 anb_settings.3.c:0 "£settings_button_south_aelantir££settings_alert_none£"
 anb_settings.3.cx:0 "£settings_button_south_aelantir_x£[Root.GetSettingsAlertSouthAelantir]"
 anb_settings.3.dd:0 "£settings_button_cannor££settings_alert_none£"
 anb_settings.3.ddx:0 "£settings_button_cannor_x£[Root.GetSettingsAlertCannor]"
 anb_settings.3.e:0 "£settings_button_deepwoods££settings_alert_none£"
 anb_settings.3.ex:0 "£settings_button_deepwoods_x£[Root.GetSettingsAlertDeepwoods]"
 anb_settings.3.f:0 "£settings_button_bulwar££settings_alert_none£"
 anb_settings.3.fx:0 "£settings_button_bulwar_x£[Root.GetSettingsAlertBulwar]"
 anb_settings.3.g:0 "£settings_button_north_sarhal££settings_alert_none£"
 anb_settings.3.gx:0 "£settings_button_north_sarhal_x£[Root.GetSettingsAlertNorthSarhal]"
 anb_settings.3.h:0 "£settings_button_south_sarhal££settings_alert_none£"
 anb_settings.3.hx:0 "£settings_button_south_sarhal_x£[Root.GetSettingsAlertSouthSarhal]"
 anb_settings.3.i:0 "£settings_button_east_sarhal££settings_alert_none£"
 anb_settings.3.ix:0 "£settings_button_east_sarhal_x£[Root.GetSettingsAlertEastSarhal]"
 anb_settings.3.j:0 "£settings_button_west_serpentspine££settings_alert_none£"
 anb_settings.3.jx:0 "£settings_button_west_serpentspine_x£[Root.GetSettingsAlertWestSerpentspine]"
 anb_settings.3.k:0 "£settings_button_east_serpentspine££settings_alert_none£"
 anb_settings.3.kx:0 "£settings_button_east_serpentspine_x£[Root.GetSettingsAlertEastSerpentspine]"
 anb_settings.3.l:0 "£settings_button_forbidden_plains££settings_alert_none£"
 anb_settings.3.lx:0 "£settings_button_forbidden_plains_x£[Root.GetSettingsAlertForbiddenPlains]"
 anb_settings.3.m:0 "£settings_button_rahen££settings_alert_none£"
 anb_settings.3.mx:0 "£settings_button_rahen_x£[Root.GetSettingsAlertRahen]"
 anb_settings.3.n:0 "£settings_button_haless££settings_alert_none£"
 anb_settings.3.nx:0 "£settings_button_haless_x£[Root.GetSettingsAlertHaless]"
 anb_settings.3.o:0 "£settings_button_gozenguun££settings_alert_none£"
 anb_settings.3.ox:0 "£settings_button_gozenguun_x£[Root.GetSettingsAlertGozenguun]"
 anb_settings.3.p:0 "£settings_button_insyaa££settings_alert_none£"
 anb_settings.3.px:0 "£settings_button_insyaa_x£[Root.GetSettingsAlertInsyaa]"
 anb_settings.3.x:0 "£settings_button_back_to_menu£"
 
 #custom loc
 settings_cannor_yes:0 "£settings_cannor£"
 settings_north_aelantir_yes:0 "£settings_north_aelantir£"
 settings_forbidden_plains_yes:0 "£settings_forbidden_plains£"
 settings_bulwar_yes:0 "£settings_bulwar£"
 settings_deepwoods_yes:0 "£settings_deepwoods£"
 settings_east_serpentspine_yes:0 "£settings_east_serpentspine£"
 settings_haless_yes:0 "£settings_haless£"
 settings_gozenguun_yes:0 "£settings_gozenguun£"
 settings_north_sarhal_yes:0 "£settings_north_sarhal£"
 settings_rahen_yes:0 "£settings_rahen£"
 settings_west_serpentspine_yes:0 "£settings_west_serpentspine£"
 settings_insyaa_yes:0 "£settings_insyaa£"
 settings_south_aelantir_yes:0 "£settings_south_aelantir£"
 settings_south_sarhal_yes:0 "£settings_south_sarhal£"
 settings_east_sarhal_yes:0 "£settings_east_sarhal£"
 settings_no:0 ""
 
 settings_alert_orange:0 "£settings_alert_orange£"
 settings_alert_red:0 "£settings_alert_red£"
 settings_alert_red_orange:0 "£settings_alert_red_orange£"
 settings_alert_none:0 "£settings_alert_none£"
 
 settings_alert_orange_main:0 "£settings_alert_orange_main£"
 settings_alert_red_main:0 "£settings_alert_red_main£\n"
 settings_alert_none_main:0 ""
 
 #tooltip
 settings_achievement_tt:0 "Disabling achievements can lead to a (very) minor increase of game performance"
 settings_achievement_disabled_tt:0 "§RAchievements can't be enabled in multiplayer§!"
 
 no_conquerors_tooltip:0 "§G"Normality is a paved road. It’s comfortable to walk, but no flowers grow on it."§!\n\nFor those that seek a standard Anbennar experience."
 great_conqueror_tooltip:0 "§O"Cowards shrink from challenges, weaklings flee from them, but warriors wink at them."§!\n\nThis option will enable §YGreat Conquerors§! for a more challenging game."
 mythical_conqueror_tooltip:0 "§R"Know thyself, know thy enemy. A thousand battles, a thousand victories."§!\n\nFor those that wish to dance with danger."
 random_conqueror_targets_tooltip:0 "§O"Change is inevitable. Growth is optional."§!\n\nEnables §YVariant Conquerors§! for unique challenges to overcome."
 delayed_conqueror_tooltip:0 "§O"Nature does not hurry, yet everything is accomplished."§!\n\nDisables §YGreat Conquerors§! until the §YAge of Unraveling§!."
 
 settings_conquerors_tt:0 "§YGreat Conquerors§!\nDynamically chosen AI countries will receive bonuses to help them consolidate their surroundings, to provide more challenging opponents for the middle and late game."
 settings_regions_tt:0 "§YDisabling Regions§!\nDisabling some parts of the world will allow you improve the game's performances."
 settings_needs_rom_dlc_tt:0 "§RThis feature requires the Rights of Man DLC§!"
 institutions_warning_tt:0 "£icon_settings_alert_red£ §RDisabling Cannor will prevent some Institutions from spawning correctly§!\n"
 tag_need_this_region_tt:0 "£icon_settings_alert_orange£ §y[Root.GetName] might have content related to this region§!"
 tag_in_this_region_tt:0 "£icon_settings_alert_red£ §R[Root.GetName]'s capital is in this region§!\n"
 disable_region_tt:0 "Disables this region to improve the game's performance.\n---------------------------\n"
 disable_all_region_tt:0 "Disables all regions."
 settings_wont_be_available_tt:0 "§RSettings are only available at the beginning of the game, you won't be able to access them later.§!"
 settings_regions_are_gonna_get_removed_tt:0 "£icon_settings_alert_red£ §RDisabled regions will be removed from the game, and you won't be able to add them back latter. This action might make the game lag for a couple seconds.§!"

 #Great Conqueror event loca
 great_conqueror.2.t:0 "A Lich-King Rises"
 great_conqueror.2.d:0 ""I throw myself upon your visage. You see all that I am, and I am perfect."\n-Theknial's Catechism, Final Page.\n\nMany have dared to attempt the foul rituals of ascension in the past, though few have succeeded in defiling mortality itself and achieving Lichdom. One cannot stomach such cruelty without a will of iron and a heart of tar. But this has not stopped the [From.Monarch.GetTitle] of [From.GetName] from spurning purity and becoming a being of pure evil: a true Lich.\n\nHordes of zombies, skeletons, and whatever horrors the Lich-King [From.Monarch.GetName] has mustered march upon the world, and we have only seen the beginning of a new necromantic demesne."
 great_conqueror.2.a:0 "We must take it upon ourselves to right their wrongs."

 lich_king_tt:0 "§RThe undead armies of [From.GetName] will sweep across Halann. We must be prepared.§!"

 great_conqueror.6.t:0 "Triumph of the Crimson Caehn"
 great_conqueror.6.d:0 "What little trade we had with the vast and wild lands of the Forbidden Plains has crept entirely to a halt in recent months. What few have managed to escape have told us why. The centaurs are unifying under a new Great Caehn, and the Forbidden Plains have erupted into a terrible war.\n\nThe grasses weep blood, they say. The peals of thunder across the plains are drowned out by the screams of the dying, and the wails of the soon-to-be dead.\n\nThere has been war for months upon months, but the Great Caehn is gaining strength, and soon the centaurs, all of the centaurs alive, will spill out beyond the Forbidden Plains. They will come for us.\n\nFirst they will send us messengers. Then they will send us scouts. Then they will send us a horde without horizon, and our lands will suffer the same fate as the Forbidden Plains."
 great_conqueror.6.a:0 "The great stampede has begun."

 seat_of_centaur_gc:0 "Seat of the Crimson Caehn"

 caehn_vc_tt:0 "§RA dreadful storm brews over the Forbidden Lands. We must prepare, lest we are blown asunder by the winds of Irdaeos.§!"

 great_conqueror.8.t:0 "The Vile One Rises"
 great_conqueror.8.d:0 "There is a place in Sarhal where the fog lies deep.\n\nIt licks at the stony hem of palaces and settles in the alleyways. One cannot always keep it out of doors. It is said that the fog itself listens to what you say, that one can never be sure of privacy in a town to which the fog has arrived. Stranger still, it is said that the fog was invited; that a realm steeped in the corruption of the three hags of Yezel Mora has pledged itself entirely to their cause.\n\nYet it is not the hags who rule in this befogged country, as they rule Yezel Mora. Instead the Wise Three have sent an apprentice, a daughter in shadow, a figure referred to only as the Vile One. Possessing terrible arcane power of her own, this Vile One advances the agenda of the hags in her own right, and has taken direct command of her inheritance.\n\nA new agent of shadow menaces Sarhal, and all right-thinking people tremble at the prospect."
 great_conqueror.8.a:0 "The Umbral Covenant has been sworn."

 umbral_covenant_gc:0 "The Umbral Horde"

 vile_one_vc_tt:0 "§RA great menace claws forth from the shadows. We must be prepared, lest we fall to the encroaching dark."
